version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - 6362:8080
    networks:
      - net
    environment:
      APP_ENVIRONMENT: production

networks:
  net: {}
